### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by FWP1001** [taylorc1009/FIGA-CVRPTW#1]
when I run the main.py  there is a problem AssertionError: assert args.algorithm is not None and args.problem_instance is not None. How to handle it？

**Comment by taylorc1009** [comment]
You need to give it the necessary arguments. `args` is the parsed arguments from the `ArgumentParser` on line 50 of main.py. You should be able to use `-h`/`--help` to see how they are used. Hope that helps
